URL = "https://ejqzmzgofrybekijpixj.supabase.co"
ANON = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVqcXptemdvZnJ5YmVraWpwaXhqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MDkzMTI4OTksImV4cCI6MjAyNDg4ODg5OX0.zxpDkBWFIgF6Ry5cVipqdK2sF8kdZc9CrBADkY2BHSE"
SERVICE_ROLE ="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVqcXptemdvZnJ5YmVraWpwaXhqIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTcwOTMxMjg5OSwiZXhwIjoyMDI0ODg4ODk5fQ.YobMLT3Zim7ZKQito_Nuiw6hoNq15mhnvl9g0_ZwRxs"
